apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "my-static-site.fullname" . }}
  namespace: {{ include "my-static-site.namespace" . }}
  labels:
    {{- include "my-static-site.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "my-static-site.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "my-static-site.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: "secret-server"
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default "latest" }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: 80
          protocol: TCP

        env:
        - name: STAGE
          value: {{ .Values.stage | upper | quote }}
        - name: SECRET_MESSAGE
          valueFrom:
            secretKeyRef:
              name: {{ .Values.siteSecret.name }}
              key: {{ .Values.siteSecret.key }}

        {{- if .Values.probes.enabled }}
        livenessProbe:
          httpGet:
            path: {{ .Values.probes.liveness.path }}
            port: http
          initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
          periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
          timeoutSeconds: {{ .Values.probes.liveness.timeoutSeconds }}
          failureThreshold: {{ .Values.probes.liveness.failureThreshold }}
        readinessProbe:
          httpGet:
            path: {{ .Values.probes.readiness.path }}
            port: http
          initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
          periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
          timeoutSeconds: {{ .Values.probes.readiness.timeoutSeconds }}
          failureThreshold: {{ .Values.probes.readiness.failureThreshold }}
        {{- end }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
