# Creates the Kubernetes Secret to store the sensitive message.
apiVersion: v1
kind: Secret
metadata:
  # Use a name specific to the release and stage to avoid collisions
  name: {{ .Values.siteSecret.name }}
  namespace: {{ include "my-static-site.namespace" . }}
  labels:
    {{- include "my-static-site.labels" . | nindent 4 }}
type: Opaque
data:
  # The key name is specified in values.yaml
  # The value is Base64 encoded as required by Kubernetes Secrets
  {{ .Values.siteSecret.key }}: {{ .Values.siteSecret.value | b64enc | quote }}

