apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-static-site.fullname" . }}
  namespace: {{ include "my-static-site.namespace" . }}
  labels:
    {{- include "my-static-site.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http 
      protocol: TCP
      name: http
  selector:
    {{- include "my-static-site.selectorLabels" . | nindent 4 }}
