replicaCount: 2 # Maybe more replicas for prod

# Use the default image, service, resources, probes from values.yaml

ingress:
  enabled: true
  hostname: "prod.my-static-site.local" # Hostname for prod
  tls:
    enabled: true

stage: prod

siteSecret:
  name: site-secret-prod # Unique secret name for prod
  key: message
  # Example secret value for prod - use Helm secrets management in real scenarios!
  value: "TopSecretProdKey"

namespace:
  create: true
  name: "prod" # Deploy into the 'prod' namespace

